### ISSUE TITLE
AST schema version is not compatible w/ 0.90.3 & swc@1.4.1

### ISSUE THREAD

**Issue by schmod** [magic-akari/swc_mut_cjs_exports#109]
Using the latest version of this plugin and the latest version of SWC, I get this error: 

```
    0: failed to invoke `swc_mut_cjs_exports` as js transform plugin at swc_mut_cjs_exports
    1: Plugin's AST schema version is not compatible with host's. Host: 1, Plugin: 2
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

`@swc/core`: 1.4.1
`swc_mut_cjs_exports`: 0.90.3

If I'm reading the versioning guidelines correctly, I believe these versions _should_ be compatible?

**Comment by magic-akari** [comment]
It might be caused by https://github.com/swc-project/swc/issues/8613. 
I will release version 0.90.6 to fix it.
