### ISSUE TITLE
Default exports are not set as configurable

### ISSUE THREAD

**Issue by devcorraliza** [magic-akari/swc_mut_cjs_exports#14]
Hello, first of all thx for the plugin, it is being very useful at jest transform.
I would like to advice you that transpiled code defines default export is not being defined through your _export function son it keeps not configurable.
```
Object.defineProperty(exports, 'default', {
  enumerable: true,
  get: () => _default
});
```
It would be great if also default property is set as configurable.

**Comment by pbomb** [comment]
We're running into this same issue and is one of the last blockers to switching from `babel-jest`. Unfortunately I don't know Rust & SWC to help fix this issue, but just wanted to voice my support for fixing it.

**Comment by pbomb** [comment]
For reference, [this is the corresponding Pull Request](https://github.com/vitejs/vite/pull/8567) that Vite made so that Vitest could correctly mock the default export of a module.

**Comment by devcorraliza** [comment]
Thx a lot for the update.
