### ISSUE TITLE
Feature Request: Support Object.assign on imported objects

### ISSUE THREAD

**Issue by shahmirn** [magic-akari/swc_mut_cjs_exports#17]
We have the following code in one of our test files:

```
import * as ProposalStore from 'views/InteractiveProposal/store/proposalStore';
```

```
Object.assign(ProposalStore, { useProposalDispatch: () => mockDispatch });
```

Which gives the following error:

  ● Test suite failed to run

    TypeError: Cannot set property useProposalDispatch of [object Object] which has only a getter
        at Function.assign (<anonymous>)

       8 | jest.mock('views/InteractiveProposal/store/actions/updateDownPaymentAndSelectedFinanceOption');
       9 | const mockDispatch = jest.fn();
    > 10 | Object.assign(ProposalStore, { useProposalDispatch: () => mockDispatch });
    
 We were able to work around it by changing the code to:
 
 ```
 jest.mock('views/InteractiveProposal/store/proposalStore', () => {
  const actual = jest.requireActual('views/InteractiveProposal/store/proposalStore');
  return {
    ...actual,
    useProposalDispatch: () => mockDispatch,
  };
});
```

But it'd be nice to support the other, existing way also.

Thanks!

**Comment by magic-akari** [comment]
Use `[[Define]]` instead of `[[Set]]`.

`Object.assign` will trigger the setter, which is not what you expect.

Try the following codes.
```JavaScript 
Object.defineProperty(ProposalStore, "useProposalDispatch", { value: () => mockDispatch });
```
