### ISSUE TITLE
Doesn't appear to work with typescript?

### ISSUE THREAD

**Issue by siosphere** [magic-akari/swc_mut_cjs_exports#18]
I've installed the jest_workaround, and setup my jest.config to pass the plugin in, 

My .swcrc file:
```
{
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "tsx": true
        }
    },
    "module": {
        "type": "commonjs"
    }
}
```
when I run I still get:
```
 ● Test suite failed to run

    TypeError: Cannot redefine property: trackCtaClicked
        at Function.defineProperty (<anonymous>)
```

Not sure what I'm doing wrong.

Package versions:
```
"@swc/cli": "^0.1.57",
"@swc/core": "^1.3.14",
"@swc/jest": "^0.2.23",
"jest_workaround": "^0.1.13"
```

**Comment by quolpr** [comment]
Have the same issue

**Comment by siosphere** [comment]
> Have the same issue

I was able to get around it, by removing all of my jest.spyOn, and replacing it with a proper mock:
```
import foobar, {someExport} from 'foobar'

jest.mock('foobar', () => {
    return {
        esModule: true,
        default: jest.fn(),
        someExport: jest.fn(),
    }
})
```

**Comment by baublet** [comment]
Thanks for the tip @siosphere, that will work for many. For our use cases, though, we need this plugin so we don't have to rewrite thousands of lines of code to use SWC instead of Babel.

And yeah, can confirm. With TypeScript, this plugin unfortunately doesn't seem to work.
