### ISSUE TITLE
SyntaxError: Unexpected token '<' after upgrading @swc/core to 1.3.39

### ISSUE THREAD

**Issue by pneme** [magic-akari/swc_mut_cjs_exports#26]
<img width="702" alt="Screenshot 2023-03-13 at 14 30 57" src="https://user-images.githubusercontent.com/107948346/224716343-dbbbb243-d5ce-4320-bf69-e065f4e66d7b.png">

**Comment by AbhiPrasad** [comment]
I'm running into this no matter what version of `@swc/core` I use, tried go to down to `1.2.0`, could be a misconfiguration of some sort?

**Comment by ryanmr** [comment]
I discovered this issue today during an upgrade:

```
    /example/test.ts:55
    describe("generate", <>()=>{});
                         ^

    SyntaxError: Unexpected token '<'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1495:14)
```

I don't think this is an [wasm plugin, but I did see this new doc](https://swc.rs/docs/plugin/selecting-swc-core).

**Comment by pneme** [comment]
Our codebase involves Nest.js and the only setup I could get working for unit test is using swc with `jest_workaround` up until 1.3.39 release.

**Comment by pneme** [comment]
@magic-akari Thanks for fixing this. Could you please publish the latest release also to npm? 🙏

**Comment by magic-akari** [comment]
> @magic-akari Thanks for fixing this. Could you please publish the latest release also to npm? 🙏

I believe it has already been published on npm.
https://www.npmjs.com/package/jest_workaround/v/0.1.16

**Comment by pneme** [comment]
@magic-akari I see it now, thanks. However I tried upgrading `jest_workaround` to `0.1.16` and `@swc/core` to `1.3.40` (even tried `1.3.39`) but reported problem still persists.

**Comment by magic-akari** [comment]
> @magic-akari I see it now, thanks. However I tried upgrading `jest_workaround` to `0.1.16` and `@swc/core` to `1.3.40` (even tried `1.3.39`) but reported problem still persists.

I have encountered a similar problem during my local testing process.
It appears that there is an issue with the caching of swc/jest.
You may attempt to resolve it by running [`jest --clearCache`](https://jestjs.io/docs/cli#--clearcache).
