### ISSUE TITLE
NextJS compatibility

### ISSUE THREAD

**Issue by paulsturgess** [magic-akari/swc_mut_cjs_exports#3]
This looks like just what I need. But when I run Jest I get all the same issues about spying. It doesn't seem to have made any difference.

I have updated the .swcrc file as per the Readme and it is highlighted in VSCode saying:

> Property experimental is not allowed

![Screenshot 2022-07-29 at 16 05 09](https://user-images.githubusercontent.com/4964/181789598-b5a60205-19bf-497a-a8f1-07222054c86b.png)

This is the full .swcrc file:

```
{
  "$schema": "http://json.schemastore.org/swcrc",
  "jsc": {
    "experimental": {
      "plugins": [["jest_workaround", {}]]
    },
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": false,
      "dynamicImport": true
    },
    "target": "es5",
    "baseUrl": ".",
    "paths": { [...]  }
  },
  "module": {
    "type": "commonjs"
  }
}
```

Installed package versions:
- "jest_workaround": "^0.1.5",
- "@swc/core": "^1.2.220",
- "@swc/jest": "^0.2.22",
- "swc-node": "^1.0.0",

I'm also using NextJS. Is there something I am missing to enable plugins for SWC ?

Thanks!

**Comment by magic-akari** [comment]
In order to locate this issue, you should check/provide the related input code and output code.
Use the same `.swcrc` file, you can get the transformed jest test file by running the swc cli.

---

I think the VSCode hint is because the JSON Schema is out of date and is not related to this issue.

**Comment by paulsturgess** [comment]
Thanks OK I can see the plugin must be working because the output from running the `swc` command line tool does show a difference if I disable the plugin.

So perhaps I am misunderstanding the use-case. I cannot redefine constants as I am currently doing in my jest tests:

```js
// my-constants.ts
export const FOO = 'foo';
export const BAR = 'bar';
```

```js
// my-demo.ts
import { FOO } from './my-constants'
export demo() { console.log({FOO}) }
```

```js
// my-demo.spec.ts
import * as MY_CONSTANTS from './my-constants';
import { demo } from './my-demo';

describe('demo', () => {
  beforeEach(() => {
    Object.defineProperty(MY_CONSTANTS, 'FOO', {
      value: 'foo-updated',
    });
  });
  it('should output my foo-updated', () => {
    demo();
  });  
})
```

Gives me the error:

>  TypeError: Cannot redefine property: FOO at Function.defineProperty (<anonymous>)

Output for `yarn swc my-constants` 

```
Successfully compiled 1 file with swc.
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
function _export(target, all) {
    for(var name in all)Object.defineProperty(target, name, {
        enumerable: true,
        get: all[name],
        configurable: true
    });
}
_export(exports, {
    FOO: function() {
        return FOO;
    },
    BAR: function() {
        return BAR;
    }
});
var FOO = "foo";
var BAR = "bar";
```

**Comment by paulsturgess** [comment]
Alternatively if I try:

```js
jest.spyOn(MY_CONSTANTS, 'FOO', 'get').mockReturnValue('updated-foo')
```

I get an explicit error:

> FOO is not declared configurable

**Comment by paulsturgess** [comment]
OK I think that NextJS is ignoring the `.swcrc`

I discovered NextJS does have support for swc plugins ([relevant PR](https://github.com/vercel/next.js/pull/36790)).

I tried it, but it still didn't change anything for me :(

**Comment by dsteinbach-ep** [comment]
I tried using with NextJS but this is the error it throws:

![Screen Shot 2022-07-29 at 4 30 19 PM](https://user-images.githubusercontent.com/95725195/181860372-8c703042-345e-4640-b33e-7ded26d85c18.png)



next.config.js
```
const withTM = require('next-transpile-modules')(['aws-amplify-react']);

module.exports = withTM({
  reactStrictMode: true,
  compiler: {
    styledComponents: true,
  },
  experimental: {
    swcPlugins: [['jest_workaround', {}]],
  },
});
```

**Comment by magic-akari** [comment]
> Thanks OK I can see the plugin must be working because the output from running the `swc` command line tool does show a difference if I disable the plugin.
> 
> So perhaps I am misunderstanding the use-case. I cannot redefine constants as I am currently doing in my jest tests:
> 
> ```js
> // my-constants.ts
> export const FOO = 'foo';
> export const BAR = 'bar';
> ```
> 
>  ```js
> // my-demo.ts
> import { FOO } from './my-constants'
> export demo() { console.log({FOO}) }
> ```
> 
>  ```js
> // my-demo.spec.ts
> import * as MY_CONSTANTS from './my-constants';
> import { demo } from './my-demo';
> 
> describe('demo', () => {
>   beforeEach(() => {
>     Object.defineProperty(MY_CONSTANTS, 'FOO', {
>       value: 'foo-updated',
>     });
>   });
>   it('should output my foo-updated', () => {
>     demo();
>   });  
> })
> ```
> 
> Gives me the error:
> 
> > TypeError: Cannot redefine property: FOO at Function.defineProperty ()
> 
> Output for `yarn swc my-constants`
> 
> ```
> Successfully compiled 1 file with swc.
> "use strict";
> Object.defineProperty(exports, "__esModule", {
>     value: true
> });
> function _export(target, all) {
>     for(var name in all)Object.defineProperty(target, name, {
>         enumerable: true,
>         get: all[name],
>         configurable: true
>     });
> }
> _export(exports, {
>     FOO: function() {
>         return FOO;
>     },
>     BAR: function() {
>         return BAR;
>     }
> });
> var FOO = "foo";
> var BAR = "bar";
> ```

I tried this example and it wroks.

https://gist.github.com/magic-akari/9ca42e3e23179ea1ad27bdc55d1ac932

```bash
git clone https://gist.github.com/9ca42e3e23179ea1ad27bdc55d1ac932.git swc_jest_example
cd swc_jest_example
pnpm i
pnpm test
```

**Comment by magic-akari** [comment]
> Is there something I am missing to enable plugins for SWC ?

This SWC plugin should be used with `@swc/jest`.
And you should add the `jest.config.js` file.

I just updated README.

**Comment by paulsturgess** [comment]
Yeah I think the issue here is that the [NextJS docs specify to configure jest](https://nextjs.org/docs/testing#setting-up-jest-with-the-rust-compiler) to use its own swc jest transformer.

If we look at the [source code](https://github.com/vercel/next.js/blob/canary/packages/next/build/jest/jest.ts#L118-L132) we can see it allows us to override or append to the `transform` rule. But that will conflict with the transform rule pointing at [swc/jest-transformer](https://github.com/vercel/next.js/blob/canary/packages/next/build/swc/jest-transformer.js) and we can see it builds the [jsc config here](https://github.com/vercel/next.js/blob/canary/packages/next/build/swc/options.js), but I don't see how we could tell it to use the `jest_workaround` plugin.

**Comment by dsteinbach-ep** [comment]
In next.config.js you can specify swc plugins (experiemental) but it throws a "Incompatible Export Type" error. Something is wrong with the wasm the jest_workaround package exports or it was built for a version that NextJs doesnt support?

Next.js depends on these SWC versions:
```
"@swc/cli": "0.1.55",
"@swc/core": "1.2.203",
"@swc/helpers": "0.4.2",
```
Unfortunately, I dont know enough about Rust to debug further. 

To see the error add this to `next.config.js`:
```
  experimental: {
    swcPlugins: [['jest_workaround', {}]],
  },
```

**Comment by magic-akari** [comment]
> In next.config.js you can specify swc plugins (experiemental) but it throws a "Incompatible Export Type" error. Something is wrong with the wasm the jest_workaround package exports or it was built for a version that NextJs doesnt support?
> 
> Next.js depends on these SWC versions:
> 
> ```
> "@swc/cli": "0.1.55",
> "@swc/core": "1.2.203",
> "@swc/helpers": "0.4.2",
> ```
> 
> Unfortunately, I dont know enough about Rust to debug further.
> 
> To see the error add this to `next.config.js`:
> 
> ```
>   experimental: {
>     swcPlugins: [['jest_workaround', {}]],
>   },
> ```

@dsteinbach-ep This happens when versions are not compatible.

The SWC plugin requires @swc/core@1.2.220. But the @swc/core in your next.js is 1.2.203

**Comment by paulsturgess** [comment]
Even if we got it working by updating `next.config.js`. Isn't the problem then that we _only_ want the plugin to run for Jest, which wouldn't be the case if we enable the plugin via the NextJS config.

**Comment by magic-akari** [comment]
> Even if we got it working by updating `next.config.js`. Isn't the problem then that we _only_ want the plugin to run for Jest, which wouldn't be the case if we enable the plugin via the NextJS config.

Not sure how to make it work.
It's better to open an issue in next.js asking how to use custom plugins with `@swc/jest` in next.js.

**Comment by dsteinbach-ep** [comment]
Can the functionality of this plugin be dependent on `process.env.NODE_ENV=test`?

**Comment by magic-akari** [comment]
> Can the functionality of this plugin be dependent on `process.env.NODE_ENV=test`?

No. This plugin is running in the wasm runtime. It should not and cannot read environment variable.
You should enable it in jest.config.js.

https://github.com/magic-akari/jest_workaround/blob/439ead5a1caa0d7671c828c52024d11d381016f2/README.md?plain=1#L19-L33

**Comment by paulsturgess** [comment]
@magic-akari thanks for your responses here. Please feel free to close this issue.
