### ISSUE TITLE
Members of unnamed re-exports cannot be redefined

### ISSUE THREAD

**Issue by wadjoh** [magic-akari/swc_mut_cjs_exports#55]
When given an export like:
```typescript
export * from './someModule'
```

And using `jest.spyOn` on a member from `someModule` an `TypeError: Cannot redefine property` error is still produced.

Re-exporting with names doesn't seem to have this problem, though:
```typescript
export * as blah from './someModule'
```
```typescript
export { foo, bar, baz } from './someModule'
```

I've created a small repo that reproduces the issue: https://github.com/wadjoh/swc-jest-workaround-bug
The re-export statement can be found in the [src/someModule/index.ts](https://github.com/wadjoh/swc-jest-workaround-bug/blob/main/src/someModule/index.ts) file in that repo.

**Comment by rowanoulton** [comment]
We're seeing this too
