### ISSUE TITLE
Optional chaining not transpiled properly

### ISSUE THREAD

**Issue by lughino** [magic-akari/swc_mut_cjs_exports#58]
Hi there,

I'm completely stuck by enabling jest with swc because of an issue with optional chaining not being transpiled properly.

To reproduce the error, you can place in a test:

```ts
const foo = [1, 2, 3];
console.log(foo[2], foo?.[2]);
```

The result of that console log is `3`, and `undefined`.

I think the problem is within this plugin as I already use swc to build my app and I checked the compiled javascript, which result in a correct working output.
There was recently an [issue](https://github.com/swc-project/swc/pull/7614) with swc that was not transpiling the optional chain.
So I also tried to upgrade the swc, cleared all the cache for swc and jest, and tried again with the same result.

**Comment by magic-akari** [comment]
I think there is nothing to do with optional chaining in this plugin.

**Comment by msolvaag** [comment]
Seeing the same. When using this plugin with the latest version of swc/core, I still see the optional chaining bug.

**Comment by rowanoulton** [comment]
@lughino I'm not certain we're seeing the same problem but since upgrading SWC to 0.79 in our project we're getting a bunch of `invalid utf8 character detected: FromUtf8Error` errors from jest. Have you seen anything of that nature?

**Comment by rowanoulton** [comment]
OK, an update: I can confirm that swc, when used as the transformer for jest unit tests in conjunction with jest_workaround, is exhibiting the same failure to transpile optional chaining we saw before we upgraded swc from 0.76 to 0.79 to resolve [this issue](https://github.com/swc-project/swc/pull/7530).

An example:

```ts
return foo() && window?.document?.createElement('webview')?.src === '';
```

Is transpiled to:

```js
return foo() && ((_this = this) === null || _this === void 0 ? void 0 : _this.) === '';
```

Throwing `SyntaxError: Unexpected token ')'`

I wonder, is all that's needed to fix jest_workaround to bump from 0.76 to 0.79?

**Comment by rowanoulton** [comment]
Renovate out here doing gods work: https://github.com/magic-akari/jest_workaround/pull/52/files

Let me know if this would _also_ require bumping [this dependency](https://github.com/magic-akari/jest_workaround/blob/master/package.json#L33) and I can throw a branch together for merge?

**Comment by msolvaag** [comment]
This ^ seems to be the most likely solution @magic-akari 🙏

**Comment by msolvaag** [comment]
Oh, nvm. Seems this is already working with the latest version. Thanks!
