### ISSUE TITLE
Cannot use it with yarn 3/pnp

### ISSUE THREAD

**Issue by Lefschetz** [magic-akari/swc_mut_cjs_exports#69]
Hi, @magic-akari 
Seem that `jest_workaround` cannot work under yarn 3 pnp. 
Here is a [example](https://github.com/Lefschetz/example) to reproduce.

I have try pnpm, it works well. But when use package manager yarn 3, it cannot to run test successfully. 
I have also try to run test using `node 16/20`, neither of them works. 

Here is the error 
```
 FAIL  src/calculate.spec.ts
  ● Test suite failed to run

    failed to get the node_modules path

      at Compiler.transformSync (.yarn/unplugged/@swc-core-virtual-4ff309335d/node_modules/@swc/core/index.js:241:29)
      at transformSync (.yarn/unplugged/@swc-core-virtual-4ff309335d/node_modules/@swc/core/index.js:348:21)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.241 s
Ran all test suites.
```

If I comment out the [line](https://github.com/Lefschetz/example/blob/79dfdc544af6d20fe25639a6ad89889d951d2994/jest.config.js#L8), the test runs successfully.

 Do I miss Any fatal config?

**Comment by magic-akari** [comment]
see https://github.com/swc-project/swc/issues/3247
