### ISSUE TITLE
Invalid left-hand side in assignmet when using swc_mut_cjs_exports

### ISSUE THREAD

**Issue by HiranmayaGundu** [magic-akari/swc_mut_cjs_exports#87]
I use [`io-ts`](https://github.com/gcanti/io-ts) in my code, and io-ts has as export named `null`. This is reexported in code as
```js
export { null } from 'io-ts'; 
``` 

This generates the following export when used with the plugin: 
```js
Object.defineProperty(exports, "null", {
    enumerable: true,
    get () {
        return _iots.null;
    },
    set (v) {
        null = v;
    },
    configurable: true
});
```

This errors out because `null = v` is invalid. 

The minimal repro of this issue can be found here: https://github.com/HiranmayaGundu/null-error-repro

**Comment by magic-akari** [comment]
This is interesting one.
I overlooked that the import names may be invalid identifier names.
