### ISSUE TITLE
Failed to invoke plugin

### ISSUE THREAD

**Issue by Codex-** [magic-akari/swc_mut_cjs_exports#98]
Possibly need to be updated to the latest swc crates?

Started getting this after updating swc:
```
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.270.26/src/plugin.rs:162:14:
failed to invoke plugin: failed to invoke plugin on 'Some("/Users/alexmiller/dev/app/node_modules/jest-runner/build/index.js")'

Caused by:
    0: failed to invoke `swc_mut_cjs_exports` as js transform plugin at swc_mut_cjs_exports
    1: RuntimeError: unreachable

Stack backtrace:
   0: _napi_register_module_v1
   1: _wasmer_vm_imported_memory32_atomic_notify
   2: _napi_register_module_v1
   3: _napi_register_module_v1
   4: _napi_register_module_v1
   5: _napi_register_module_v1
   6: _napi_register_module_v1
```

I had to update my own plugin too 😅

**Comment by magic-akari** [comment]
https://github.com/magic-akari/swc_mut_cjs_exports/actions/runs/7604856396/job/20708309028

It's OK in the CI result.
What's the SWC version you are using?

**Comment by Codex-** [comment]
Yeah my mistake, it works currently too, but won't work with `@swc/core@1.3.106` probably with the changes introduced for import phase:
https://swc.rs/docs/plugin/selecting-swc-core#088x-
https://github.com/tc39/proposal-source-phase-imports

**Comment by Matt561** [comment]
Is there a plan to update this package to work with the lastest @swc/core version?

**Comment by Codex-** [comment]
I'm using latest core with the latest version of this package without issue, if you're experiencing a specific issue you should probably open a new issue
